### ISSUE TITLE
Can't Load Files

### ISSUE THREAD

**Issue by aslepekis** [3ll3d00d/pypolarmap#6]
When I go to load measurements, nothing seems to happen. The file box remains blank and no measurements appear in the other windows. I have tried .WAV .TXT and REW files, but after selecting a folder, nothing seems to happen and when navigating to the desired folder, it appears empty from the pypolarmap file explorer, I select the desired folder but nothing seems to happen.

**Comment by 3ll3d00d** [comment]
There are 2 issues here

1. I need to add some feedback to the user to say what happened
2. the wav file loader is mishandling the file name so blows up

I'll fix them both in the next build

note that the file name pattern it looks for `.*_?([HV]([0-9]+)).*` which basically means the file must contain H or V followed by the angle. In your case posted on diya, the files are just 0-180 so it ignores them as it doesn't know if they are H or V measurements. Prefix with H and it will load them (and then blow up on issue 2 above).

**Comment by 3ll3d00d** [comment]
fixed the wav loader in https://github.com/3ll3d00d/pypolarmap/commit/e95ac35487b0d69e7e2ff0135a3001ab8fd98f04

**Comment by aslepekis** [comment]
My installation of PyPolar seems to be ignoring everything but .txt files; in the "ignored files" column I can see all the other files in the folder (all prefixed with "H"), but it doesn't load them. It does load .txt files just fine, however.

**Comment by 3ll3d00d** [comment]
You will need to be more specific about what you are doing, i.e. I need you a specific set of actions that will reproduce the problem reliably. This may mean providing the files/folder you are using too.

**Comment by 3ll3d00d** [comment]
closing as fixed by https://github.com/3ll3d00d/pypolarmap/releases/tag/0.0.1-alpha.5
